import type { Organization, Output, Risk, Timeline } from '../core/types';
import { Tag, money, percent } from './shared';
import { ShieldCheck } from 'lucide-react';

export function RiskGraph({ org, output, selected, onSelect, defended = false, blast = false, compact = false }: { org: Organization; output: Output; selected: string; onSelect: (id: string) => void; defended?: boolean; blast?: boolean; compact?: boolean }) {
  const positions: Record<string, [number, number]> = {};
  const ids = output.blast.map(b => b.entry), nodes = ids.map(id => org.assets.find(a => a.id === id)!);
  // Layer by longest parent distance to keep all DAG edges moving left to right.
  const depth: Record<string, number> = {};
  for (const id of ids) depth[id] = Math.max(0, ...org.edges.filter(e => e.to === id).map(e => (depth[e.from] ?? 0) + 1));
  const maxDepth = Math.max(1, ...Object.values(depth));
  for (let d = 0; d <= maxDepth; d++) { const group = ids.filter(id => depth[id] === d); group.forEach((id, i) => positions[id] = [76 + d / maxDepth * 478, 55 + (i + .5) / group.length * 225]); }
  const probability = blast ? output.blast.find(b => b.entry === selected)?.probabilities ?? output.risk.probabilities : (defended ? output.after : output.risk).probabilities;
  const path = (defended ? output.optimal : output.portfolios[0]).responses[0]?.path ?? [];
  return <div className={`risk-graph ${compact ? 'compact' : ''}`}><div className="graph-caption"><span><span className="legend-dot orange"/>{blast ? 'Conditional blast radius' : 'Modeled compromise probability'}</span><Tag tag="COMPUTED"/></div><svg viewBox="0 0 635 345" role="img" aria-label="Interactive asset dependency graph"><defs><marker id={`arrow-${defended}-${blast}`} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#a8b4c1"/></marker></defs>
    {org.edges.map(e => { const [x, y] = positions[e.from], [tx, ty] = positions[e.to], active = path.some((p, i) => p === e.from && path[i + 1] === e.to); return <g key={e.from + e.to}><path d={`M${x + 23},${y} C${(x + tx) / 2},${y} ${(x + tx) / 2},${ty} ${tx - 27},${ty}`} className={`graph-edge ${active ? 'active' : ''}`} markerEnd={`url(#arrow-${defended}-${blast})`} style={{ strokeWidth: 1 + e.weight.value * 3 }}><title>{e.reason}</title></path></g>; })}
    {nodes.map((a, i) => { const [x, y] = positions[a.id], p = probability[i], high = p > .16; return <g className={`graph-node ${selected === a.id ? 'selected' : ''}`} key={a.id} transform={`translate(${x},${y})`} role="button" tabIndex={0} aria-label={`Inspect ${a.label}`} onClick={() => onSelect(a.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') onSelect(a.id); }}><circle r={27 + p * 9} fill={high ? '#fff0e3' : '#e9f2f7'} stroke={high ? '#dca06b' : '#acc4d3'}/><g stroke={high ? '#aa642b' : '#4a748d'} fill="none" strokeWidth="1.6"><rect x="-9" y="-11" width="18" height="18" rx="3"/><path d="M-5,-5h10 M-5,0h10 M-3,7v5 M-7,12h14"/></g><text y="49" className="graph-label">{a.label}</text><text y="67" className="graph-probability" data-provenance="COMPUTED">{percent(p)} · computed</text>{a.id === 'vendor' && <text y="-41" className="graph-preview">preview relationship</text>}</g>; })}
  </svg><div className="graph-footer"><span><i className="line-key"/>Adaptive attacker route</span><span>Click an asset to trace its risk <span aria-hidden="true">↗</span></span></div></div>;
}
export function Distribution({ risk }: { risk: Risk }) {
  const max = Math.max(...risk.histogram.map(b => b.count), 1), total = risk.histogram.at(-1)?.high || 1;
  return <div className="distribution"><div className="chart-label">Simulated loss outcomes <Tag tag="COMPUTED"/></div><svg viewBox="0 0 540 190" role="img" aria-label="Monte Carlo loss distribution histogram"><line x1="15" y1="142" x2="525" y2="142" stroke="#e6e9ed"/>{risk.histogram.map((b, i) => <rect key={i} x={18 + i * 31.5} y={140 - b.count / max * 103} width="24" height={Math.max(1, b.count / max * 103)} rx="3" fill={b.low > risk.p90 ? '#d7e1e5' : i === 0 ? '#95b6ad' : '#486d6a'}><title data-provenance="COMPUTED">{money(b.low)}–{money(b.high)}: {b.count} trials · COMPUTED</title></rect>)}<line x1={18 + risk.ale / total * 500} y1="24" x2={18 + risk.ale / total * 500} y2="144" stroke="#212e43" strokeDasharray="4 4"/><line x1={18 + risk.p90 / total * 500} y1="24" x2={18 + risk.p90 / total * 500} y2="144" stroke="#ca8448" strokeDasharray="4 4"/><text x="18" y="172" data-provenance="COMPUTED">₹0</text><text x="510" y="172" textAnchor="end" data-provenance="COMPUTED">{money(total)}</text></svg><div className="chart-legend"><span><i className="legend-dot navy"/>Expected loss</span><span><i className="legend-dot orange"/>Tail loss · <span data-provenance="COMPUTED">P90</span></span></div></div>;
}
export function TimelineChart({ events }: { events: Timeline[] }) {
  const max = Math.max(...events.map(e => e.ale), 1), points = events.map((e, i) => `${20 + i / Math.max(1, events.length - 1) * 500},${115 - e.ale / max * 85}`).join(' ');
  return <svg className="timeline-chart" viewBox="0 0 540 140" role="img" aria-label="Risk history"><path d={`M20,125 L${points.replaceAll(' ', ' L')} L520,125 Z`} fill="#edf4f0"/><polyline points={points} fill="none" stroke="#417865" strokeWidth="2"/>{events.map((e, i) => <circle key={i} cx={20 + i / Math.max(1, events.length - 1) * 500} cy={115 - e.ale / max * 85} r="4" fill={e.alert ? '#c47739' : '#417865'}><title data-provenance={e.tag}>{e.event}: {money(e.ale)}</title></circle>)}</svg>;
}
export function ControlList({ org, output }: { org: Organization; output: Output }) { return <div className="control-list">{org.controls.filter(c => output.optimal.ids.includes(c.id)).map(c => <div key={c.id}><ShieldCheck size={19}/><div><strong>{c.name}</strong><small>Modeled effect · <span data-provenance="ASSUMED">{percent(c.efficacy.value)} <Tag tag="ASSUMED"/></span></small></div><span data-provenance="ASSUMED">{money(c.cost.value)}</span></div>)}{!output.optimal.ids.length && <p className="empty-copy">No controls fit this budget. Increase the budget to compare feasible plans.</p>}</div>; }
