import type { Source } from './types.js';
export const sources: Source[] = [
  {
    id: 'stackelberg',
    title: 'Conitzer & Sandholm · Computing the Optimal Strategy to Commit to',
    url: 'https://www.cs.cmu.edu/~conitzer/commitEC06.pdf',
    date: '2006',
    note: 'Commitment and follower-response framework. This prototype enumerates pure defender actions; it does not implement the paper’s general mixed-strategy formulations.',
  },
  {
    id: 'dobss',
    title: 'Paruchuri et al. · Playing Games for Security',
    url: 'https://u.cs.biu.ac.il/~krauss/data/articles/AAMAS_2008.pdf',
    date: '2008',
    note: 'Bayesian Stackelberg security games and multiple attacker types. This prototype uses a finite enumeration backend, not a claimed implementation of DOBSS.',
  },
  {
    id: 'interdiction',
    title: 'Israeli & Wood · Shortest-path network interdiction',
    url: 'https://onlinelibrary.wiley.com/doi/10.1002/net.10039',
    date: '2002',
    note: 'Reference for network interdiction. Linear shortest-path duality does not establish an exact reduction for dependent Bayesian cascades.',
  },
  {
    id: 'ct',
    title: 'Cert Spotter · SRMIST certificate transparency snapshot',
    url: 'https://api.certspotter.com/v1/issuances?domain=srmist.edu.in&include_subdomains=true&expand=dns_names',
    date: '2026-09-25',
    note: 'Public certificate hostnames verified during development. A certificate does not establish service availability, ownership of backing systems, or vulnerabilities.',
  },
  {
    id: 'crt',
    title: 'crt.sh · certificate transparency search',
    url: 'https://crt.sh/?q=%25.srmist.edu.in',
    date: '2026-09-25',
    note: 'Primary live collector. Requests fall back to Cert Spotter and then a dated local snapshot if unavailable.',
  },
  {
    id: 'epss',
    title: 'FIRST · Exploit Prediction Scoring System',
    url: 'https://www.first.org/epss/data',
    date: '2026-09-25',
    note: 'Probability of exploitation activity observed globally in the next thirty days; not organization compromise probability.',
  },
  {
    id: 'kev',
    title: 'CISA · Known Exploited Vulnerabilities data',
    url: 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json',
    date: '2026-09-25',
    note: 'Evidence of exploitation in the wild. Membership does not demonstrate that an example institution is vulnerable.',
  },
  {
    id: 'nvd',
    title: 'NIST · National Vulnerability Database API',
    url: 'https://nvd.nist.gov/developers/vulnerabilities',
    date: '2026-09-25',
    note: 'CVE descriptions and severity. An asset association needs software/version evidence.',
  },
  {
    id: 'attack',
    title: 'MITRE ATT&CK · knowledge base and limitations',
    url: 'https://attack.mitre.org/resources/faq/',
    date: '2026-09-25',
    note: 'Behavior taxonomy built from public reports. This is not a population frequency dataset; all attacker priors in this prototype are assumptions.',
  },
  {
    id: 'ibm',
    title: 'IBM · India Cost of a Data Breach',
    url: 'https://in.newsroom.ibm.com/India-Records-its-Highest-Average-Cost-of-a-Data-Breach-2026',
    date: '2026-08-03',
    note: 'India mean cost per breach: ₹25.5 crore. Context only, not an annual expected loss and not a validation set for this model.',
  },
  {
    id: 'dpdp',
    title: 'Digital Personal Data Protection Act · original statute',
    url: 'https://www.meity.gov.in/static/uploads/2024/06/2bf1f0e9f04e6fb4f8fef35e82c42aa5.pdf',
    date: '2023-08-11',
    note: 'Schedule: up to ₹250 crore for failure to take reasonable security safeguards. Statutory ceiling only, excluded from expected loss. This panel does not assess commencement, applicable rules or legal compliance.',
  },
  {
    id: 'cert',
    title: 'CERT-In · directions under the Information Technology Act',
    url: 'https://www.cert-in.org.in/PDF/CERT-In_Directions_70B_28.04.2022.pdf',
    date: '2022-04-28',
    note: 'Covered entities must report specified incidents within six hours of noticing them or being brought to notice. Context, not a compliance determination.',
  },
  {
    id: 'qaoa',
    title: 'Farhi, Goldstone & Gutmann · A Quantum Approximate Optimization Algorithm',
    url: 'https://arxiv.org/abs/1411.4028',
    date: '2014-11-14',
    note: 'Basis of the small state-vector circuit simulator. No quantum advantage is claimed.',
  },
  {
    id: 'lucas',
    title: 'Lucas · Ising formulations of many NP problems',
    url: 'https://arxiv.org/abs/1302.5843',
    date: '2014-02-14',
    note: 'Binary optimization and constraint penalties.',
  },
  {
    id: 'qubo',
    title: 'Glover, Kochenberger & Du · A Tutorial on Formulating and Using QUBO Models',
    url: 'https://arxiv.org/abs/1811.11538',
    date: '2018-11-28',
    note: 'QUBO formulation reference. Our pairwise risk objective is explicitly a surrogate.',
  },
];
